[package]
name = "runmod"
version = "1.0.0"
edition = "2024"
license = "Apache-2.0"
description = "A rust libary to speed up development"

[dependencies]
lexical-core = "1.0.6"
regex = "1.12.2"

[profile.bench]
debug = true
